id = "csharp"
name = "C#"
description = "C# & Razor Support"
version = "1.1.0"
schema_version = 1
authors = [
    "fminkowski <fminkowski@gmail.com>",
    "Fabian Freimueller <fabianfreimueller@gmail.com>",
    "Kevin Müller <kevin.mueller1@outlook.com>"
]
repository = "https://github.com/kevin-mueller/zed-csharp"
snippets = "./snippets/csharp.json"

languages = ["CSharp", "Razor", "csproj"]

[language_servers.roslyn-official]
name = "Roslyn (Official)"
languages = ["CSharp", "Razor"]

[language_servers.roslyn-official.language_ids]
CSharp = "csharp"
Razor = "razor"

[language_servers.html-in-razor]
name = "HTML"
languages = ["Razor"]

[language_servers.html-in-razor.language_ids]
Razor = "html"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "cac6d5fb595f5811a076336682d5d595ac1c9e85"

[grammars.razor]
repository = "https://github.com/tris203/tree-sitter-razor"
commit = "1e8ec29b7179329ce7cffcfae2c5347e8a00f7cf"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "5000ae8f22d11fbe93939b05c1e37cf21117162d"
path = "xml"

[debug_adapters.netcoredbg]
schema_path = "debug_adapter_schemas/netcoredbg.json"

[debug_locators.csharp-project-runner]

[[capabilities]]
kind = "process:exec"
command = "dotnet"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "git"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "cat"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "test"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "find"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "echo"
args = ["**"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["--download"]

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["qwadrox", "netcoredbg", "**"]

[[capabilities]]
kind = "download_file"
host = "objects.githubusercontent.com"
path = ["**"]